services:
  - type: web
    name: zoro-document-portal
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: FLASK_APP
        value: run.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///instance/pdf_portal.db
      - key: UPLOAD_FOLDER
        value: uploads
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
